<?php

// Navigation Translation Strings for Menu Titles
$zume_navigation_menu = array(
    __( 'Home', 'zume' ),
    __( 'Dashboard', 'zume' ),
    __( 'About', 'zume' ),
    __( 'Resources', 'zume' ),
    __( 'FAQs', 'zume' ),
    __( 'Resources', 'zume' ),
    __( 'Training', 'zume' ),
    __( 'Course', 'zume' ),
    __( 'Course Overview', 'zume' ),
    __( 'Groups', 'zume' ),
    __( 'Checklist', 'zume' ),
    __( 'Get a Coach', 'zume' ),
    __( 'Download Guidebook', 'zume' ),
    __( 'Overview', 'zume' ),
    __( 'Settings', 'zume' ),
    __( 'Profile', 'zume' ),
    __( 'Admin', 'zume' ),
    __( 'Logout', 'zume' ),
    __( 'Login', 'zume' ),
    __( 'Register', 'zume' ),
    __( 'Three-Month Plan', 'zume' ),
    __( 'Vision', 'zume' ),
    __( 'Mobile App', 'zume' ),
    __( 'Zúme Training is an on-line and in-life learning experience designed for small groups who follow Jesus to learn how to obey His Great Commission. Best Disciple Making Movements training online.', 'zume' ),
    __( 'This 3/3 group meeting pattern can be used for a simple church (or home church), a leadership cell, or peer mentoring group.', 'zume' ),
    __( 'A Person of Peace is someone who is open to hearing the Good News of Jesus and is excited to draw others into the conversation about Him.', 'zume' ),
    __( 'Zúme training equips participants in basic disciple-making and simple church planting multiplication principles, processes, and practices.', 'zume' ),
    __( 'Jesus taught that we do and say matters now and in eternity. Accountability groups are no more than brothers and sisters walking together in truth and love.', 'zume' ),
    __( 'Members of a simple church can start new churches while still being a part of their primary church family. This can grow into a city-wide body of believers.', 'zume' ),
    __( 'Baptism is a picture of our new life, soaked in the image of Jesus, transformed in obedience to God. Here\'s a short guide on how to baptize someone.', 'zume' ),
    __( 'The coaching checklist is a simple tool you can use to help guide you as you assist others through various parts of disciple maturity or training like Zúme.', 'zume' ),
    __( 'Learn to help Christian followers of Jesus become a producers in their faith, not just a consumers. Disciples are to be doers of the word, not hearers only.', 'zume' ),
    __( 'To see God’s family grow far and grow in faithfulness, then think of disciple-making like ducklings. Become a follower and a leader at the same time.', 'zume' ),
    __( 'If we want to see the kingdom of God grow rapidly we need to expect and even encourage non-sequential growth.', 'zume' ),
    __( 'Every disciple needs to be equipped to see where the Kingdom isn’t.', 'zume' ),
    __( 'Faithfulness is better than knowledge when it comes to identifying who we should spend time with in making disciples who make disciples.', 'zume' ),
    __( 'Frequently asked questions about Zúme Training. Who runs Zúme? How much does it cost? What languages is it translated into?', 'zume' ),
    __( 'The four fields tool is a diagnostic chart used by a leadership cell to reflect on the status of current efforts and the kingdom activity around them.', 'zume' ),
    __( 'Generational mapping helps leaders in a movement understand the growth around them. Here is a example of a generational map and the individual church layout', 'zume' ),
    __( 'Learn how God uses ordinary people to tell others about Jesus. His plan has always been that disciples make disciples. We all have a role to play.', 'zume' ),
    __( 'Zúme Training is an on-line and in-life learning experience designed for small groups who follow Jesus to learn how to obey His Great Commission.', 'zume' ),
    __( 'Pace matters because our eternity is determined in the short time we call “life”. Over time a faster pace can result in exponetial growth of disciples.', 'zume' ),
    __( 'Use this peer mentoring group format for leader-to-leader mentoring, in order to strengthen individuals, simple churches, and even networks of churches.', 'zume' ),
    __( 'Prayer Walking is just what it sounds like - praying to God while walking around.', 'zume' ),
    __( 'Your story of your relationship with God is called your testimony. Everybody has a story. Sharing your testimony is a chance to practice yours.', 'zume' ),
    __( 'Be faithful with the people God has already put in you life. We call this relational stewardship. Making a list of 100 is a way to start!', 'zume' ),
    __( 'Zúme Training resources are free tools for disciple-makers who want to make disciples wo multiply.', 'zume' ),
    __( 'It\'s important to have a simple definition of disciple and church. A disciple loves God, loves people, and makes disciples. A church is a spiritual family.', 'zume' ),
    __( 'The S.O.A.P.S. Bible Reading format will help you understand, obey and share even more. Use this tool to show others how to study the Bible.', 'zume' ),
    __( 'We breathe in. We breathe out. Life. In God’s Kingdom, spiritual breathing is hearing (breathing in) and obeying God (breathing out).', 'zume' ),
    __( 'The BLESS prayer pattern gives five ways (Body, Labor, Emotional, Social, and Spiritual) you can pray for people you meet during your prayer walk.', 'zume' ),
    __( 'One way to share God’s Story is by explaining what’s happened from God’s Creation to His Judgement at the end of this age. Practice this story yourself.', 'zume' ),
    __( 'The kingdom economy is when we are faithful to OBEY and SHARE what the Lord has shared with us, then He promises to share even more.', 'zume' ),
    __( 'Holy Communion or “The Lord’s Supper” is a way to celebrate our intimate connection and ongoing relationship with Jesus. Here’s a simple way to lead it.', 'zume' ),
    __( 'The training cycle is used for maturing disciples through four distinct steps of spiritual growth. The steps include: MODEL, ASSIST, WATCH and LEAVE.', 'zume' ),
    __( 'Zúme is a community of practice for those who want to see disciple making movements. Let\'s saturate the world with multiplying disciples together.', 'zume' ),
    __( 'Find videos and pages to help you learn what it means to be a follower of Jesus and to help others follow Jesus with you.', 'zume' ),
    __( 'When someone chooses to follow Jesus, how do you help them move down the right path? Start by vision casting the greatest blessing awaiting them.', 'zume' ),
);
